
spring:
  datasource:
    test1:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
      username: root
      password: root
    test2:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
      username: root
      password: root
mybatis:
  # 配置类型别名
  typeAliasesPackage: com.zsx.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis/mapper/*.xml
